version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.1
    - 7.13.13
    - 7.13.15
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.13
    - 7.12.14
    - 7.12.16
    - 7.12.17
    - 7.13.12
    - 7.13.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.0
    - 7.13.12
    - 7.13.8
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: danger
    versions:
    - 10.6.1
