allowBuilds:
  core-js: true
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - snooplogg@9.0.0
  - undici@8.6.0
  - '@oxfmt/binding-android-arm-eabi@0.58.0 || 0.60.0'
  - '@oxfmt/binding-android-arm64@0.58.0 || 0.60.0'
  - '@oxfmt/binding-darwin-arm64@0.58.0 || 0.60.0'
  - '@oxfmt/binding-darwin-x64@0.58.0 || 0.60.0'
  - '@oxfmt/binding-freebsd-x64@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-arm64-musl@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-x64-gnu@0.58.0 || 0.60.0'
  - '@oxfmt/binding-linux-x64-musl@0.58.0 || 0.60.0'
  - '@oxfmt/binding-openharmony-arm64@0.58.0 || 0.60.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.58.0 || 0.60.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.58.0 || 0.60.0'
  - '@oxfmt/binding-win32-x64-msvc@0.58.0 || 0.60.0'
  - '@oxlint/binding-android-arm-eabi@1.73.0 || 1.75.0'
  - '@oxlint/binding-android-arm64@1.73.0 || 1.75.0'
  - '@oxlint/binding-darwin-arm64@1.73.0 || 1.75.0'
  - '@oxlint/binding-darwin-x64@1.73.0 || 1.75.0'
  - '@oxlint/binding-freebsd-x64@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-arm64-gnu@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-arm64-musl@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-riscv64-musl@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-s390x-gnu@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-x64-gnu@1.73.0 || 1.75.0'
  - '@oxlint/binding-linux-x64-musl@1.73.0 || 1.75.0'
  - '@oxlint/binding-openharmony-arm64@1.73.0 || 1.75.0'
  - '@oxlint/binding-win32-arm64-msvc@1.73.0 || 1.75.0'
  - '@oxlint/binding-win32-ia32-msvc@1.73.0 || 1.75.0'
  - '@oxlint/binding-win32-x64-msvc@1.73.0 || 1.75.0'
  - '@vitest/coverage-v8@4.1.10'
  - '@vitest/expect@4.1.10'
  - '@vitest/mocker@4.1.10'
  - '@vitest/pretty-format@4.1.10'
  - '@vitest/runner@4.1.10'
  - '@vitest/snapshot@4.1.10'
  - '@vitest/spy@4.1.10'
  - '@vitest/utils@4.1.10'
  - oxfmt@0.58.0 || 0.60.0
  - oxlint@1.73.0 || 1.75.0
  - vitest@4.1.10
